# name: PR Closer

# on:
#   pull_request:
#     types: [opened, reopened]


# jobs:
#   close-pull-request:
#     runs-on: ubuntu-latest
#     name: Close Pull Request
#     steps:
#       - uses: codelytv/no-pull-requests@v1
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           message: 🙅 We don't accept Pull Requests!


on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hey can you check this link [instead](https://google.com)?
